# Generated by Django 3.0.5 on 2020-08-21 16:08

from django.db import migrations, models
import gateways.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProccessPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=20, validators=[gateways.validators.credit_card_validator])),
                ('card_holder', models.CharField(max_length=30)),
                ('expiration_date', models.DateTimeField(validators=[gateways.validators.expiration_date_validator])),
                ('security_code', models.CharField(max_length=3, validators=[gateways.validators.security_code_validator])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3, validators=[gateways.validators.amount_validator])),
            ],
        ),
    ]
